// Strings for the copied screens (src/ui), taken from ned-landing/src/content/copy.ts (only the keys used here).
// Local edits for the video, per BRIEF section 2 and the build request:
//   replaced "licensed partner", the "Nobody, including N.E.D ..." line, "You never hold crypto" and the old link domain;
//   emptied strings with unapproved release wording; the matching elements are hidden in the render (props in the screens).
// Do not add wording here that is not in the landing copy or in BRIEF.md.
export const copy = {
  screens: {
    status: {
      clock: "9:41",
      devnet: "Devnet · test money",
    },
    homeVN: {
      greeting: "Good morning,",
      name: "Vinh",
      handle: "vinh",
      profileLabel: "Your profile, Vinh",
      heroLabel: "Locked for you",
      heroWhole: "≈ 13,010,000",
      heroUnit: " VND",
      heroSubEstimate: "example, estimated",
      heroSubRest: " · $500.00 · 1 contract · rate of 2 Oct",
      flagTitle: "Vietnamese đồng (VND)",
      flagLabel: "Flag of Vietnam",
      quickActions: "Quick actions",
      share: {
        label: "Share @vinh",
        aria: "Share @vinh: send your username to a client",
        sub: "To a client",
      },
      records: {
        label: "Records",
        aria: "Records: what you received",
        sub: "Your earnings",
      },
      statA: {
        label: "Received this month",
        value: "≈ 0 VND",
      },
      statB: {
        label: "Active contracts",
        value: "1",
      },
      needsTitle: "Needs your action",
      needs: [
        {
          title: "Submit milestone 1 · due in 9 days",
          sub: "Landing page design · ≈ 6,500,000 VND",
          icon: "submit",
          tone: "purple",
        },
      ],
      contractsTitle: "Your contracts",
      seeAll: "See all",
      rows: [
        {
          seed: "mia",
          title: "Landing page design",
          party: "from @mia",
          deadline: "Milestone 1 due 12 Oct",
          status: "Locked · work in progress",
          tone: "purple",
          total: "≈ 13,010,000 VND",
          totalSub: "$500.00 · estimate",
        },
      ],
      suggestedTitle: "Suggested for you",
      suggested: {
        share: "Share your @username with a client",
        devnet: "What devnet and \"simulated\" mean",
        records: "Keep a record of what you receive",
      },
      nav: {
        label: "Main",
        home: "Home",
        contracts: "Contracts",
        records: "Records",
        settings: "Settings",
      },
    },
    homeIntl: {
      greeting: "Good morning,",
      name: "Mia",
      handle: "mia",
      profileLabel: "Your profile, Mia",
      heroLabel: "USDC balance",
      heroWhole: "0.00",
      heroUnit: " USDC",
      heroSub: "Devnet test money",
      flagTitle: "US dollar · USDC is a dollar stablecoin",
      flagLabel: "Flag of the United States",
      quickActions: "Quick actions",
      actions: {
        newContract: {
          label: "New contract",
          aria: "New contract: lock USDC per milestone for a freelancer",
        },
        receive: {
          label: "Receive",
          aria: "Receive USDC",
        },
        send: {
          label: "Send",
          aria: "Send USDC",
        },
      },
      statA: {
        label: "Locked in your contracts",
        value: "500.00 USDC",
      },
      statB: {
        label: "Locked for you",
        value: "0.00 USDC",
      },
      needsTitle: "Needs your action",
      noNeedsText: "",
      contractsTitle: "Your contracts",
      seeAll: "See all",
      rows: [
        {
          seed: "vinh",
          title: "Landing page design",
          party: "to @vinh",
          deadline: "Milestone 1 due 12 Oct",
          status: "Locked · work in progress",
          tone: "purple",
          total: "500.00 USDC",
          totalSub: "total",
        },
      ],
      suggestedTitle: "Suggested for you",
      suggested: {
        lock: "Lock a milestone for a freelancer",
        devnet: "What devnet and \"simulated\" mean",
        records: "Keep a record of what you receive",
      },
      nav: {
        label: "Main",
        home: "Home",
        contracts: "Contracts",
        records: "Records",
        settings: "Settings",
      },
    },
    homeVNReleased: {
      heroWhole: "≈ 6,500,000",
      heroSubRest: " · $250.00 · 1 contract · rate of 2 Oct",
      statA: {
        label: "Received this month",
        value: "≈ 6,500,000 VND",
      },
      needs: [
        {
          title: "Submit milestone 2 · due in 16 days",
          sub: "Landing page design · ≈ 6,500,000 VND",
          icon: "submit",
          tone: "purple",
        },
      ],
      rows: [
        {
          seed: "mia",
          title: "Landing page design",
          party: "from @mia",
          deadline: "Milestone 2 due 19 Oct",
          status: "Locked · work in progress",
          tone: "purple",
          total: "≈ 13,010,000 VND",
          totalSub: "$500.00 · estimate",
        },
      ],
    },
    homeIntlReleased: {
      heroWhole: "250.00",
      statA: {
        label: "Locked in your contracts",
        value: "250.00 USDC",
      },
      rows: [
        {
          seed: "vinh",
          title: "Landing page design",
          party: "to @vinh",
          deadline: "Milestone 2 due 19 Oct",
          status: "Locked · work in progress",
          tone: "purple",
          total: "500.00 USDC",
          totalSub: "total",
        },
      ],
    },
    contractAccept: {
      back: "Back",
      title: "Accept contract",
      job: "Landing page design",
      from: "from @mia",
      total: "≈ 13,010,000 VND",
      totalSubEstimate: "example, estimated",
      totalSubRest: " · $500.00 · rate of 2 Oct 2026",
      milestones: [
        "Milestone 1 · submit by 12 Oct, 18:00 · review 3 days",
        "Milestone 2 · submit by 19 Oct, 18:00 · review 3 days",
      ],
      question: "Where should your earnings go?",
      groupLabel: "Where earnings go",
      vnd: {
        title: "VND to my Vietnamese bank account",
        body: "A payout partner (simulated in the demo) converts outside Vietnam and sends VND to your bank. Bank details are collected by the partner, not by N.E.D. Simulated in this demo.",
      },
      simulated: "SIMULATED",
      vnOnly: "You live in Vietnam, so earnings arrive in VND only. Receiving USDC in a wallet is for people who live outside Vietnam (change this in Settings).",
      warn: {
        strong: "This can't be changed later.",
        rest: " You never type an address: earnings go only to the destination you pick here.",
      },
      fees: {
        label: "Fees",
        ned: "N.E.D fee",
        nedV: "None during the pilot",
        network: "Network fee",
        networkV: "~0.000005 SOL",
        networkSub: "devnet test SOL",
        partner: "Payout partner fee",
        partnerV: "Set by the partner",
      },
      slide: "Slide to accept",
    },
    contractLock: {
      back: "Back",
      title: "Lock for @vinh",
      totalLabel: "Total to lock",
      total: "500.00 USDC",
      totalSub: "Landing page design · 2 milestones",
      destLabel: "Earnings go to",
      dest: "VND via payout partner",
      simulated: "SIMULATED",
      milestones: [
        {
          k: "Milestone 1 · 250.00 USDC",
          v: "by 12 Oct, 18:00",
        },
        {
          k: "Milestone 2 · 250.00 USDC",
          v: "by 19 Oct, 18:00",
        },
      ],
      reviewLabel: "Review time",
      review: "3 days each",
      rulesLabel: "Contract rules",
      rules: [
        "Released when the client approves, or anyone can press Release now after the review deadline, unless the client requested changes in time.",
        "Refunded to the client if a submission deadline is missed.",
        "No instruction lets N.E.D move the locked money.",
      ],
      balanceLabel: "Your balance",
      balance: "500.00 USDC",
      afterLabel: "After locking",
      after: "0.00 USDC",
      fees: {
        label: "Fees",
        ned: "N.E.D fee",
        nedV: "None during the pilot",
        network: "Network fee",
        networkV: "~0.000005 SOL",
        networkSub: "devnet test SOL",
        partner: "Payout partner fee",
        partnerV: "Set by the partner",
      },
      slide: "Slide to lock",
    },
    contractLocked: {
      headline: "500.00 USDC locked",
      sub: "Landing page design is locked in the program vault. @vinh can start work.",
      vaultTitle: "Locked in program vault",
      vaultSub: "Owned by the program, not by N.E.D · ",
      vaultAddress: "9vLt…Qm4x",
      explorer: "Explorer",
      rulesLabel: "Contract rules",
      rules: [
        "Released when the client approves, or anyone can press Release now after the review deadline, unless the client requested changes in time.",
        "Refunded to the client if a submission deadline is missed.",
        "No instruction lets N.E.D move the locked money.",
      ],
      primary: "View contract",
      secondary: "Back to Home",
    },
    contractLockedVN: {
      headline: "Locked ≈ 13,010,000 VND · you can start",
      subEstimate: "example, estimated",
      subRest: " · $500.00. @mia locked the full contract in the program vault. Submit milestone 1 by 12 Oct, 18:00.",
      primary: "Submit milestone 1",
      secondary: "Back to Home",
    },
    milestoneReview: {
      back: "Back",
      title: "Review milestone 1",
      job: "Landing page design · Milestone 1",
      by: "by @vinh · submitted 3 Oct, 00:31",
      amt: "250.00 USDC",
      amtSub: "to VND via payout partner",
      cdBefore: "",
      cd: "2 days 17 h",
      checkLabel: "Check a link",
      checkHelp: "Paste the link @vinh sent you. We compare its fingerprint with the one saved on-chain.",
      link: "https://example.com/vinh/landing-v1",
      linkChanged: "https://example.com/vinh/landing-v2",
      placeholder: "https://",
      match: "Matches what was submitted ✓",
      noMatch: "Doesn't match what was submitted",
      onchain: "On-chain fingerprint ",
      fees: {
        label: "Fees",
        ned: "N.E.D fee",
        nedV: "None during the pilot",
        network: "Network fee",
        networkV: "~0.000005 SOL",
        networkSub: "devnet test SOL",
        partner: "Payout partner fee",
        partnerV: "Set by the partner",
      },
      simulated: "SIMULATED",
      slide: "Slide to release",
    },
    milestoneReleased: {
      devnet: "Devnet · test money",
      teddyAlt: "",
      chip: "Released",
      explorer: "View on Explorer",
      fees: "N.E.D fee: none during the pilot · Network fee ~0.000005 SOL (devnet test SOL)",
      done: "Done",
      receiptLabel: "Receipt",
      simLine: "VND payout simulated in this demo ",
      simulated: "SIMULATED",
      client: {
        headline: "Released to Vinh",
        sub: "Landing page design · Milestone 1 · 250.00 USDC",
        receipt: [
          {
            k: "Contract",
            v: "Landing page design · Milestone 1",
          },
          {
            k: "Amount",
            v: "250.00 USDC",
            focus: "rel-amount-client",
          },
          {
            k: "To",
            v: "VND via payout partner (simulated)",
          },
          {
            k: "Released by",
            v: "You (@mia)",
          },
        ],
      },
      anyone: {
        headline: "250.00 USDC released to @vinh",
        sub: "Logo refresh · to VND via payout partner (simulated)",
        receipt: [
          {
            k: "Contract",
            v: "Logo refresh",
          },
          {
            k: "Amount",
            v: "250.00 USDC",
          },
          {
            k: "To",
            v: "VND via payout partner (simulated)",
          },
          {
            k: "Released by",
            v: "You (anyone can, after the review time)",
          },
        ],
      },
      refund: {
        chip: "Refunded to client",
        headline: "250.00 USDC refunded to @mia",
        sub: "Landing page design · Milestone 1 · the submission deadline passed.",
        receipt: [
          {
            k: "Contract",
            v: "Landing page design · Milestone 1",
          },
          {
            k: "Amount",
            v: "250.00 USDC",
          },
          {
            k: "To",
            v: "@mia (client)",
          },
          {
            k: "Reason",
            v: "Deadline passed",
          },
        ],
      },
      freelancerVN: {
        headline: "Released to payout partner",
        subAmount: "≈ 6,500,000 VND (",
        subEstimate: "example, estimated",
        subRest: ") · $250.00 · rate of 2 Oct 2026. The partner sends VND to your bank; this demo stops here.",
        receipt: [
          {
            k: "Contract",
            v: "Landing page design · Milestone 1",
          },
          {
            k: "Amount",
            v: "≈ 6,500,000 VND (example, estimated)",
            focus: "rel-amount-you",
          },
          {
            k: "To",
            v: "Payout partner (simulated)",
          },
          {
            k: "From",
            v: "@mia",
          },
        ],
      },
    },
    anyoneAction: {
      back: "Back",
      devnet: "Devnet · test money",
      parties: "client @mia · freelancer @vinh",
      bgAmt: "250.00 USDC",
      sheetLabel: "Anyone action",
      fees: {
        label: "Fees",
        ned: "N.E.D fee",
        nedV: "None during the pilot",
        network: "Network fee",
        networkV: "~0.000005 SOL",
        networkSub: "devnet test SOL",
        partner: "Payout partner fee",
        partnerV: "Set by the partner",
      },
      simulated: "SIMULATED",
      cancel: "Cancel",
      release: {
        bgHead: "Logo refresh",
        bgTitle: "Logo refresh",
        bgStatus: "Submitted · review time passed",
        title: "Release now",
        text: "The review time has passed. Anyone can release this milestone to the freelancer's destination.",
        rows: [
          {
            k: "Milestone",
            v: "Logo refresh · 250.00 USDC",
          },
          {
            k: "Review time ended",
            v: "3 Oct, 00:41",
          },
          {
            k: "Goes to",
            v: "VND via payout partner for @vinh (simulated)",
          },
        ],
        slide: "Slide to release",
      },
      refund: {
        bgHead: "Landing page design",
        bgTitle: "Landing page design · Milestone 1",
        bgStatus: "Not submitted · deadline passed",
        title: "Refund now",
        text: "The submission deadline passed. Anyone can refund this milestone to the client.",
        rows: [
          {
            k: "Milestone",
            v: "Landing page design · Milestone 1",
          },
          {
            k: "Submission deadline",
            v: "12 Oct, 18:00 (passed)",
          },
          {
            k: "Goes to",
            v: "@mia (client)",
          },
        ],
        slide: "Slide to refund",
      },
    },
    disclosures: {
      back: "Back",
      title: "Disclosures",
      intro: "Please read these before you lock or receive anything. Version 1.0.0 · pilot on Solana devnet.",
      rows: [
        {
          id: "devnet",
          title: "Devnet only",
          text: "This demo runs on Solana devnet with test money. Nothing here has real value.",
        },
        {
          id: "kyc",
          title: "No KYC yet",
          text: "N.E.D does not check anyone’s identity in this version.",
        },
        {
          id: "phone",
          title: "Phone numbers are not verified",
          text: "We don’t send a code. A number on a profile may not belong to that person.",
        },
        {
          id: "audit",
          title: "The program is not audited",
          text: "The Solana program that locks and releases USDC has not had a security audit.",
        },
        {
          id: "partner",
          title: "The payout partner is simulated",
          text: "No payout partner is connected in this demo. No VND is sent to any bank.",
        },
        {
          id: "fees",
          title: "Network fees use test SOL",
          text: "Each action costs about 0.000005 test SOL on devnet. N.E.D charges no fee during the pilot.",
        },
        {
          id: "vn",
          title: "After release in the Vietnam path",
          text: "Once a milestone is released to the payout partner, you rely on that partner to send you the VND.",
        },
        {
          id: "circle",
          title: "Circle can freeze USDC addresses",
          text: "USDC is issued by Circle, which can freeze an address. N.E.D cannot undo that.",
        },
        {
          id: "public",
          title: "Public on-chain",
          text: "Contract titles and delivery-link fingerprints are public. N.E.D never stores your delivery link or bank details.",
        },
        {
          id: "advice",
          title: "Not advice",
          text: "This is not legal, tax or financial advice.",
        },
      ],
    },
  },
  web: {
    contractNew: {
      brand: {
        mark: "N.E.D",
        name: "Workspace",
      },
      devnet: "Devnet · test money",
      wallet: {
        handle: "mia",
        label: "Your wallet, @mia",
        sub: "USDC wallet",
      },
      breadcrumb: {
        root: "Workspace",
        sep: "/",
        here: "New contract",
      },
      heading: "New contract",
      steps: [
        "1 · Brief",
        "2 · @vinh accepts",
        "3 · You lock",
        "4 · Work starts",
      ],
      freelancer: {
        heading: "Freelancer",
        name: "Vinh Nguyen",
        handle: "@vinh",
        sub: "Chooses where earnings go when accepting",
        change: "Change",
      },
      job: {
        heading: "The job",
        titleLabel: "Title",
        title: "Landing page design",
        scopeLabel: "What you need",
        scope: "A one-page landing site for our new budgeting app, desktop and mobile. Use the copy and the brand guide linked below. Milestone 1 is design only; milestone 2 is the build.",
        scopePlaceholder: "Describe the work, who it is for and anything the freelancer must use.",
        refsLabel: "References",
        refs: [
          "https://drive.example.com/brand-guide-v3.pdf",
          "https://docs.example.com/landing-copy-v2",
        ],
        refAddLabel: "Add a reference link",
        refPlaceholder: "Paste a link to a brand guide, copy or example",
        add: "Add",
      },
      milestones: {
        heading: "Milestones",
        note: "",
        amountLabel: "Amount (USDC)",
        dateLabel: "Submit by",
        reviewLabel: "Review time after submit",
        reviews: [
          {
            v: "1m",
            label: "1 min (devnet demo)",
          },
          {
            v: "3d",
            label: "3 days",
          },
          {
            v: "7d",
            label: "7 days",
          },
        ],
        doneWhen: "Done when…",
        doneWhenNote: "The freelancer checks these before submitting; you check them before releasing.",
        critPlaceholder: "Add something you can check, e.g. “Works on mobile”",
        add: "Add",
        errNoCrit: "Add at least one “done when” item.",
        addMilestone: "+ Add milestone",
        list: [
          {
            name: "Wireframes and visual design",
            amt: "250",
            date: "2026-10-12T18:00",
            dateShort: "12 Oct",
            review: "3d",
            crit: [
              "Desktop and mobile layouts",
              "Colours and fonts from the brand guide",
              "Figma file with named components",
              "Copy from the brief, no placeholder text",
            ],
          },
          {
            name: "Build and launch",
            amt: "250",
            date: "2026-10-19T18:00",
            dateShort: "19 Oct",
            review: "3d",
            crit: [
              "Page live on a test link",
              "Matches the approved design",
              "Source code in a Git repository",
            ],
          },
        ],
      },
      summary: {
        total: "Total to lock",
        unit: " USDC",
        after: " · locked after @vinh accepts",
        fingerprint: "Brief fingerprint",
        fingerprintNote: "Changes as you type. When you create, it is saved on-chain and cannot change. @vinh confirms the same fingerprint when accepting, so you both agree on one brief.",
        checkedTitle: "Checked before you sign",
        checked: "At least 24 h to work before the first deadline (60 s on devnet) · review time of at least 60 s · up to 5 milestones · title up to 32 characters · at least one “done when” item per milestone.",
        create: "Create contract",
        createNote: "Opens your wallet to confirm. No money moves at this step.",
      },
      created: {
        heading: "Contract created",
        body: "Send this invite link to @vinh. The brief travels inside it, encrypted: the part after # is the key, and browsers never send that part to a server.",
        link: "unihackfest-2026.vercel.app/c/7XqP2mWc#k=Qm4tY8vR2LkN9sQe",
        copy: "Copy link",
        fingerprint: "Brief fingerprint · on-chain",
        next: "Next",
        nextText: "@vinh accepts, then you lock ",
        view: "View contract",
        back: "Back to Workspace",
      },
    },
    walletPanel: {
      who: {
        mia: {
          handle: "mia",
          shortAddr: "9PZw…rhkW",
        },
        vinh: {
          handle: "vinh",
          shortAddr: "4Fq8…Lw2c",
        },
      },
      devnet: "Devnet · ",
      fullView: "Open in full view",
      close: "Close wallet",
      app: {
        dialog: "Your N.E.D Wallet",
        label: "N.E.D Wallet",
      },
      sign: {
        request: {
          before: "Request from ",
          app: "N.E.D Workspace",
          after: " · unihackfest-2026.vercel.app",
        },
        kicker: "Confirm to sign",
        cancel: "Cancel",
        footer: "Signed with the wallet linked to your Google account. N.E.D never holds your money.",
        create: {
          dialog: "Confirm: Create contract",
          title: "Create contract",
          rows: [
            {
              k: "Contract",
              v: "Landing page design",
            },
            {
              k: "Freelancer",
              v: "@vinh",
            },
            {
              k: "Milestones",
              v: "2 · 500.00 USDC total",
              sub: "Locked later, after @vinh accepts",
            },
            {
              k: "Brief fingerprint",
              v: "{fp}",
              sub: "Saved on-chain, cannot change",
              mono: true,
            },
            {
              k: "Network fee",
              v: "~0.000005 SOL",
              sub: "devnet test SOL",
            },
            {
              k: "N.E.D fee",
              v: "None during the pilot",
            },
          ],
          note: "No money moves yet. @vinh reads the brief from your invite link and confirms the same fingerprint when accepting.",
          confirm: "Create",
        },
        submit: {
          dialog: "Confirm: Submit milestone 1",
          title: "Submit milestone 1",
          rows: [
            {
              k: "Contract",
              v: "Landing page design",
            },
            {
              k: "For",
              v: "@mia",
            },
            {
              k: "Amount",
              v: "≈ 6,500,000 VND",
              sub: "$250.00 · example, estimated · rate of 2 Oct",
            },
            {
              k: "Delivery fingerprint",
              v: "{fp}",
              sub: "Saved on-chain with the chain clock",
              mono: true,
            },
            {
              k: "Deadline",
              v: "12 Oct 2026, 18:00",
              sub: "On time · 9 days left",
            },
            {
              k: "Network fee",
              v: "~0.000005 SOL",
              sub: "devnet test SOL",
            },
          ],
          note: "After you submit, @mia has until 15 Oct, 18:00 to review. Anyone can press Release now after the review deadline, unless the client requested changes in time.",
          confirm: "Submit",
        },
      },
    },
    submit: {
      brand: {
        mark: "N.E.D",
        name: "Workspace",
      },
      devnet: "Devnet · test money",
      wallet: {
        handle: "vinh",
        label: "Your wallet, @vinh",
        sub: "Vietnam view · VND",
      },
      breadcrumb: {
        root: "Workspace",
        sep: "/",
        contract: "Landing page design",
        here: "Milestone 1",
      },
      heading: "Submit milestone 1",
      sub: "Landing page design · Wireframes and visual design · for @mia",
      timer: "Submit by 12 Oct, 18:00 · 9 days left",
      links: {
        heading: "Links to your work",
        body: "Use links that point at one fixed version (a Figma version, a Git commit, a shared file), so what @mia opens is what you delivered.",
        list: [
          {
            label: "Figma · version 2214",
            url: "https://www.figma.com/design/Lp7Qx/landing?version-id=2214",
          },
          {
            label: "GitHub · commit 3f9a1c2",
            url: "https://github.com/vinh-ng/landing/tree/3f9a1c2",
          },
        ],
        pinned: "Fixed version",
        remove: "Remove ",
        addLabel: "Add a link",
        placeholder: "https://",
        add: "Add",
      },
      files: {
        heading: "Files",
        body: "Files stay on your computer. We read each one here and keep only its fingerprint, so @mia can check the file you share with her is the same one.",
        drop: "Drop files here or choose files",
        list: [
          {
            name: "landing-v1.fig",
            size: "4.2 MB",
            sha: "3f9a…c21e",
          },
          {
            name: "export-desktop.png",
            size: "1.1 MB",
            sha: "b81d…07f4",
          },
        ],
        fingerprint: " · fingerprint ",
        remove: "Remove ",
      },
      note: {
        label: "Note to @mia",
        value: "Both layouts are on the page “Final” in Figma. Components are named as in the brand guide.",
        placeholder: "What is in this delivery and where to look first.",
      },
      check: {
        heading: "Check against the brief",
        count: (n: number, of: number) => `${n} of ${of} ticked`,
        body: "What @mia wrote under “Done when”. Only for you: ticks are not saved on-chain.",
        items: [
          "Desktop and mobile layouts",
          "Colours and fonts from the brand guide",
          "Figma file with named components",
          "Copy from the brief, no placeholder text",
        ],
      },
      aside: {
        label: "Before you submit",
        comesLabel: "Comes to you after release",
        comesWhole: "≈ 6,500,000",
        comesUnit: " VND",
        comesSubEstimate: "example, estimated",
        comesSubRest: " · $250.00 · rate of 2 Oct · to your bank via the payout partner",
        askedTitle: "What @mia asked for",
        asked: "A one-page landing site for our new budgeting app, desktop and mobile. Use the copy and the brand guide linked below. Milestone 1 is design only…",
        briefFp: "Brief fingerprint",
        briefFpV: "0x2831…3b17",
        accepted: "You accepted",
        readBrief: "Read the full brief",
        deliveryFp: "Delivery fingerprint",
        deliveryNote: "Made from your links, file fingerprints and note. Only this goes on-chain; the delivery itself is encrypted with the contract key, so only you and @mia can read it.",
        onTimeTitle: "How on-time is decided",
        onTime: "The program accepts a submit only up to 12 Oct, 18:00 and records the time from the chain clock, not from your computer. After that, the milestone can be refunded to @mia.",
        notAll: "Some “Done when” items are not ticked. You can still submit.",
        submit: "Submit milestone 1",
        submitNote: "Opens your wallet to confirm. You cannot edit a delivery after submitting.",
      },
      done: {
        heading: "Submitted · in review",
        body: "@mia sees your delivery in her Workspace and on her phone. Anyone can press Release now after the review deadline (15 Oct, 18:00), unless the client requested changes in time.",
        recorded: "Recorded at",
        recordedV: "3 Oct 2026, 00:31 · chain clock",
        deadline: "Deadline",
        deadlineV: "12 Oct 2026, 18:00",
        onTime: "On time",
        fingerprint: "Delivery fingerprint",
        comes: "Comes to you",
        comesV: "≈ 6,500,000 VND",
        comesSubEstimate: "example, estimated",
        comesSubRest: " · $250.00 · rate of 2 Oct",
        explorer: "View on Explorer",
        back: "Back to Workspace",
      },
    },
  },
  real: {
    notYet: {
      label: "NOT YET:",
      items: [
        {
          text: "no identity checks (KYC),",
          row: "kyc",
        },
        {
          text: "no security audit,",
          row: "audit",
        },
        {
          text: "no neutral arbiter yet,",
          row: null,
        },
        {
          text: "no lawyer review yet,",
          row: null,
        },
        {
          text: "USDC is issued by Circle which can freeze an address.",
          row: "circle",
        },
      ],
    },
  },
} as const;
